### ISSUE TITLE
Trying to run qc.nf and it's failing findRelatedIndiv

### ISSUE THREAD

**Issue by raonyguimaraes** [h3abionet/h3agwas#25]
Hi there,

I'm trying to run this pipeline but I'm getting some errors:

./nextflow run qc.nf -profile docker

Error executing process > 'findRelatedIndiv (1)'

Caused by:
  Process `findRelatedIndiv (1)` terminated with an error exit status (1)

Command executed [/netapp/raony/gwas/src/h3agwas/templates/removeRelInds.py]:

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  Traceback (most recent call last):
    File "/usr/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2890, in get_loc
      return self._engine.get_loc(key)
    File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/index.pyx", line 128, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/index_class_helper.pxi", line 91, in pandas._libs.index.Int64Engine._check_type
  KeyError: '1'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "pandas/_libs/index.pyx", line 672, in pandas._libs.index.BaseMultiIndexCodesEngine.get_loc
    File "/usr/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2892, in get_loc
      return self._engine.get_loc(self._maybe_cast_indexer(key))
    File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/index.pyx", line 128, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/index_class_helper.pxi", line 91, in pandas._libs.index.Int64Engine._check_type
  KeyError: '1'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 2815, in get_loc_level
      return (self._engine.get_loc(key), None)
    File "pandas/_libs/index.pyx", line 675, in pandas._libs.index.BaseMultiIndexCodesEngine.get_loc
  KeyError: ('1', '1')
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File ".command.sh", line 46, in <module>
      rel, deg = getDegrees(remove) 
    File ".command.sh", line 33, in getDegrees
      deg[x]=deg[x]+1
    File "/usr/lib/python3.6/site-packages/pandas/core/series.py", line 1106, in __getitem__
      return self._get_with(key)
    File "/usr/lib/python3.6/site-packages/pandas/core/series.py", line 1120, in _get_with
      return self._get_values_tuple(key)
    File "/usr/lib/python3.6/site-packages/pandas/core/series.py", line 1168, in _get_values_tuple
      indexer, new_index = self.index.get_loc_level(key)
    File "/usr/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 2817, in get_loc_level
      raise KeyError(key) from e
  KeyError: ('1', '1')

Any ideas what could be wrong?

**Comment by shaze** [comment]
@raonyguimaraes I have pushed some changes from a dev branch. Please see if this fixes it

**Comment by raonyguimaraes** [comment]
Hi @shaze 

Yes that actually did fix the error! Would be good to add continuous integration to this pipeline. I still see some warnings about publishing some files, but that's ok.

Thank you so much!

WARN: Failed to publish file: /netapp/raony/gwas/src/h3agwas/work/61/519b9ad7af6d8e40add2354e084e91/out.bim; to: /netapp/raony/gwas/src/h3agwas/output/out.bim [copy] -- See log file for details
WARN: Failed to publish file: /netapp/raony/gwas/src/h3agwas/work/61/519b9ad7af6d8e40add2354e084e91/out.fam; to: /netapp/raony/gwas/src/h3agwas/output/out.fam [copy] -- See log file for details
WARN: Failed to publish file: /netapp/raony/gwas/src/h3agwas/work/61/519b9ad7af6d8e40add2354e084e91/out.bed; to: /netapp/raony/gwas/src/h3agwas/output/out.bed [copy] -- See log file for details
Completed at: 26-Sep-2019 15:34:49
Duration    : 1m 12s
CPU hours   : (a few seconds)
Succeeded   : 32

**Comment by shaze** [comment]
Dear Raony

Thanks — yes making this nf-core compliant is one of our goals.

As an aside the warning is due to teh fact that your output directory already had files in it


We appreciate feedback

Regards

Scott

> On 26 Sep 2019, at 5:36 PM, Raony Guimaraes <notifications@github.com> wrote:
>
> Closed #25.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

This communication is intended for the addressee only. It is confidential. If you have received this communication in error, please notify us immediately and destroy the original message. You may not copy or disseminate this communication without the permission of the University. Only authorised signatories are competent to enter into agreements on behalf of the University and recipients are thus advised that the content of this message may not be legally binding on the University and may contain the personal views and opinions of the author, which are not necessarily the views and opinions of The University of the Witwatersrand, Johannesburg. All agreements between the University and outsiders are subject to South African Law unless the University agrees in writing to the contrary.
